# Generated by Django 4.2.1 on 2023-05-15 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
