# Generated by Django 4.2.1 on 2023-05-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_rename_nombre_departamento_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fkdepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.departamento')),
            ],
        ),
    ]
