# Generated by Django 4.2.1 on 2023-05-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
