# Generated by Django 4.2.1 on 2023-05-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
