# Generated by Django 4.2.1 on 2023-05-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('idAlmacen', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('Fksku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.producto')),
            ],
        ),
    ]
