# Generated by Django 4.2.1 on 2023-05-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaAlmacen',
            fields=[
                ('idEntradaAlmacen', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEntrada', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('Fksku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.producto')),
            ],
        ),
    ]
