# Generated by Django 4.2.1 on 2023-05-29 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0011_remove_almacen_nombreproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPedido', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('Fksku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.producto')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.empleado')),
            ],
        ),
    ]
