# Generated by Django 4.2.1 on 2023-06-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaalmacen',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
