# Generated by Django 4.2.1 on 2023-06-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0013_entradaalmacen_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaalmacen',
            name='resultado',
        ),
    ]
