# Generated by Django 4.2.1 on 2023-06-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0019_entradaalmacen_totalp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaalmacen',
            name='totalP',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
