# Generated by Django 4.2.1 on 2023-06-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0020_alter_entradaalmacen_totalp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaalmacen',
            name='totalP',
        ),
    ]
