# Generated by Django 4.2.1 on 2023-06-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0021_remove_entradaalmacen_totalp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='alorTotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
