# Generated by Django 4.2.1 on 2023-06-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0023_remove_pedido_alortotal_pedido_valortotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valorTotal',
        ),
    ]
