# Generated by Django 4.2.1 on 2023-06-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0024_remove_pedido_valortotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigoBarras',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
